const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.resolve(__dirname,'..');
const surf=fs.readFileSync(path.join(root,'shaders/surface.glsl'),'utf8');
const gpu=fs.readFileSync(path.join(root,'js/river-gpu.js'),'utf8');
const version=fs.readFileSync(path.join(root,'VERSION.txt'),'utf8');
assert.match(version,/^VERSION 0\.5\.172$/m);
assert.match(gpu,/riverGpuCatmullDir/);
assert.match(gpu,/riverGpuDetailedLandAt/);
assert.match(gpu,/if\(!riverGpuDetailedLandAt\(core,dx,dy,dz\)\)return false;/);
assert.match(gpu,/if\(!riverGpuDetailedLandAt\(core,dx,dy,dz\)\)return;/);
assert.match(surf,/float riverBasinPermit147\(vec3 p\)/);
assert.match(surf,/float r=0\.020;/);
assert.match(surf,/riverGeomProc\*riverPermit/);
assert.match(surf,/float mouthPermit = ss\(0\.006,0\.085,riverPhys\)/);
assert.doesNotMatch(surf,/riverVectorNearest|uRiverVecOn|great-circle chord/i);
assert.doesNotMatch(surf,/riverGeomProc\*physRiverHalo/);
console.log('river-basin-visual.test.js: OK');
