const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.resolve(__dirname,'..');
const terrain=fs.readFileSync(path.join(root,'shaders/terrain.glsl'),'utf8');

/* 0.5.75: collision belts may contain several ridges, but they must not be
   generated by a periodic distance-to-seam cosine. That old expression made
   kilometre-scale perfectly smooth dark ribbons visible from orbit. */
assert.doesNotMatch(terrain,/cos\s*\(\s*belt\.y\s*\*/,
  'tectonic relief must not stamp periodic stripes from distance to a plate seam');
assert.match(terrain,/float foldWarp = 0\.5 \+ 0\.5\*fbm/,
  'fold morphology needs a non-periodic warp field');
assert.match(terrain,/float foldA = ridged/,
  'collision relief should retain broken ridge structure');
assert.match(terrain,/float foldB = 0\.5 \+ 0\.5\*fbm/,
  'a second unrelated field must break long smooth ridge arcs');
assert.match(terrain,/0\.72 \+ 0\.28\*folds/,
  'irregular folds may modulate the tectonic envelope without becoming the envelope itself');

console.log('tectonic-morphology.test.js: OK');
